# -*- coding: utf-8 -*-
"""Gradient_descent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ldrZrOWT5ab6Y74YXA60efk8nBYUMBlN
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import pprint
import matplotlib.pyplot as plt

# %matplotlib inline
#%precision 4
#np.set_printoptions(precision=4)
import pylab as pl

from google.colab import drive
drive.mount("/content/gdrive")
#on running this it will ask permission to mount with google drive. please click ok and allow. this program does not access any of the
# google drive documents except dataset which is uploaded

#/%from google.colab import files
#/%uploaded = files.upload()
#/%for func in uploaded.keys():
#/%       print('User uploaded file "{name}"'.format(name=func))

from google.colab import drive
drive.mount("/content/gdrive")

from numpy import genfromtxt
mylist=genfromtxt("/content/gdrive/My Drive/Colab Notebooks/A2Q2Data_train.csv", delimiter=',')
print("The given dataset is:")
print(mylist)

from numpy import genfromtxt
testlist=genfromtxt("/content/gdrive/My Drive/Colab Notebooks/A2Q2Data_test.csv", delimiter=',')
print("The given test dataset is:")
print(testlist)

xtrain=mylist.T[:-1]

ytrain=mylist.T[-1]

Y= np.dot(xtrain,xtrain.transpose())
Y=np.linalg.inv(Y)
Y=np.dot(Y,xtrain)
w=np.dot(Y,ytrain)

wt=np.random.rand(100,)/10000

stepsize=1/(10**6)
iterations=10000
temp=np.dot(xtrain,xtrain.transpose())
#temp.shape
temp=np.dot(temp,wt)
temp.shape
gradient=temp-(np.dot(xtrain,ytrain))
gradient=gradient*2

xtest=testlist.T[:-1]

ytest=testlist.T[-1]

def calculateError(wt):
  temp=np.dot(wt.transpose(),xtest)
  error=temp-ytest
  errorsum=0;
  for i in range(500):
    errorsum+=(error[i]**2)
  return errorsum

xplot=[]
yplot=[]
error=calculateError(wt)

preverror=0
i=0
while((abs(preverror-error))>0.000001):
  preverror=error
  wtnext=wt-(gradient*stepsize)
  wt=wtnext
  temp=np.dot(xtrain,xtrain.transpose())    #calculating gradient 
  #temp.shape
  temp=np.dot(temp,wt)
  temp.shape
  gradient=temp-(np.dot(xtrain,ytrain))
  gradient=gradient*2
  gradient.shape
  diff=np.linalg.norm(wt-w)
  xplot.append(diff)
  yplot.append(i)
  error=calculateError(wt)
  i=i+1

print("Error on test data using gradient descent is:",error)

plt.plot(yplot,xplot)
plt.ylabel("||wt-wml||")
plt.xlabel("iterations")
plt.show()