# -*- coding: utf-8 -*-
"""linear_regression_analytical.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1saA5cLljvMAiSTcZcHtOFs-U0hFhHuwZ
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import pprint
import matplotlib.pyplot as plt

# %matplotlib inline
#%precision 4
#np.set_printoptions(precision=4)
import pylab as pl

from google.colab import drive
drive.mount("/content/gdrive")
#on running this it will ask permission to mount with google drive. please click ok and allow. this program does not access any of the
# google drive documents except dataset which is uploaded

#from google.colab import files
#uploaded = files.upload()
#for func in uploaded.keys():
#       print('User uploaded file "{name}"'.format(name=func))

from numpy import genfromtxt
mylist=genfromtxt("/content/gdrive/My Drive/Colab Notebooks/A2Q2Data_train.csv", delimiter=',')
print("The given train dataset is:")
print(mylist)

from numpy import genfromtxt
testlist=genfromtxt("/content/gdrive/My Drive/Colab Notebooks/A2Q2Data_test.csv", delimiter=',')
print("The given test data is:")
print(testlist)

print("dimension of train dataset is:",mylist.shape)
print("dimesnion of test datset is:",testlist.shape)

xtrain=mylist.T[:-1]

ytrain=mylist.T[-1]

Y= np.dot(xtrain,xtrain.transpose())
Y=np.linalg.inv(Y)
Y=np.dot(Y,xtrain)
w=np.dot(Y,ytrain)
print("The calculated w is:")
print(w)

xtest=testlist.T[:-1]

ytest=testlist.T[-1]

temp=np.dot(w.transpose(),xtrain)
error=temp-ytrain
errorsum=0;
for i in range(500):
  errorsum+=(error[i]**2)

print("The squared sum of error on train data for the calculated w is:", errorsum)

temp=np.dot(w.transpose(),xtest)
error=temp-ytest

errorsum=0;
for i in range(500):
  errorsum+=(error[i]**2)

print("The squared sum of error on test data for the calculated w is:", errorsum)